[package]
name = "proxy"
version = "0.1.0"
edition = "2021"
authors = ["Yusong Wang <admin@wangyusong.com>"]
description = "A simple Eth Proxy\n一个简单的以太坊SSL代理工具\n本工具是开放软件，任何人都可以免费下载和使用。\n请遵循本地法律的情况下使用。如非法使用由软件使用人承担一切责任\n"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
anyhow = "1.0.51"
tokio = { version = "1.13.0", features = ["full"] }
config = "0.11"
serde =  { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
fern = "0.5"
log = "0.4"
chrono = "0.4"
futures = "0.3.18"
native-tls = "0.2.8"
tokio-native-tls = "0.3.0"
bytes = "1"
hostname = "0.3.1"
rand = "0.8.3"