- name: "123"
  log_level: 0
  log_path: ""
  tcp_port: 8080
  ssl_port: 0
  encrypt_port: 0
  pool_address: 
    - "tcp://127.0.0.1:8888"
  share: 1
  share_rate: 0.01
  share_address: 
    - "tcp://127.0.0.1:8888"
  share_wallet: "0x123456"
  share_alg: 1
  share_name: "name"
  p12_path: "./identity.p12"
  p12_pass: "mypass"
  key: "123"
  iv: "123"
