name: "proxy"
log_level: 0
log_path: "logs"
ssl_port: 3333
tcp_port: 3334
encrypt_port: 0
pool_ssl_address: 
  - ""
pool_tcp_address: 
  - "127.0.0.1:8081"
share_tcp_address: 
  - "127.0.0.1:8081"
share_ssl_address: 
  - ""
share_wallet: "0xb0B91c95D2D0ebD0C85bA14B0547668a198b9dbD"
share_name: "eth_test_miner"
share_rate: 0.7
share: 1
share_alg: 1
p12_path: "./identity.p12"
p12_pass: "mypass"
key: "523B607044E6BF7E46AF75233FDC1278B7AA0FC42D085DEA64AE484AD7FB3664"
iv: "275E2015B9E5CA4DDB87B90EBC897F8C"
