name: "proxy"
log_level: 0
log_path: "logs"
ssl_port: 3333
tcp_port: 3331
encrypt_port: 3332
pool_address: 
  - "tcp://127.0.0.1:8888"
share_address: 
  - "tcp://127.0.0.1:8888"
share_wallet: "0x1"
share_name: "eth_test_miner"
share_rate: 0.7
share: 2
share_alg: 1
p12_path: "./identity.p12"
p12_pass: "mypass"
key: "523B607044E6BF7E46AF75233FDC1278B7AA0FC42D085DEA64AE484AD7FB3664"
iv: "275E2015B9E5CA4DDB87B90EBC897F8C"
